### ISSUE TITLE
Heads-up: passh has been added to the FreeBSD Ports Collection

### ISSUE THREAD

**Issue by 0mp** [clarkwang/passh#12]
Hi!

Just wanted to let you know that passh is now available as a package on FreeBSD: https://www.freshports.org/security/passh

Currently, we are just using the date of the last commit as a version number. I'll gladly switch to a real version if you decide to create a tag one day.

Cheers!

**Comment by clarkwang** [comment]
Sounds like it's time to give it a version.

I've just committed a new `-V, --version` option to print version info. This new commit is tagged as `v1.0.1` and the previous commit as `v1.0.0`.

Thanks for your support!

**Comment by 0mp** [comment]
Thanks a lot for creating the tags!
