### ISSUE TITLE
Complementary Project : `PasshPapyrusScribe`

### ISSUE THREAD

**Issue by FrancoisCapon** [clarkwang/passh#17]
Hello,

Passh is very usefull, with it I can easly "have a tty in a webshell". :wink: 

I want to use it to write "passh scripts", so I published a little project to help to write this "passh scripts" :

- https://github.com/FrancoisCapon/PasshPapyrusScribe

Thanks for passh :+1:

**Comment by clarkwang** [comment]
I know very little about web stuff so I cannot understand what you're doing but I'm glad you find passh useful. :)
