### ISSUE TITLE
What is the argument of connection host port plz?

### ISSUE THREAD

**Issue by fox85** [clarkwang/passh#18]
I read the readme , but can't find any mention for the argument of port  :)

**Comment by clarkwang** [comment]
What do you mean by "connection host port"?

**Comment by fox85** [comment]
I'm sorry , the port of ssh host

**Comment by clarkwang** [comment]
Still not clear what your question is. `passh -h` does not mention ssh host or port. To use it with ssh you can

~~~
passh -p PASSWORD ssh host ...
# if your ssh server is using a non-default port
passh -p PASSWORD ssh -p 2222 host ...
~~~

**Comment by fox85** [comment]
thank you!
