### ISSUE TITLE
Usage Example on Travis-CI

### ISSUE THREAD

**Issue by nelsonic** [clarkwang/passh#2]
Hi @clarkwang! ☀️ 
I am attempting to use `passh` to input the password for an RSA key on Travis-CI.
The `passh.c` compiles successfully, but when I try to _use_ `passh` in an `ssh` command,
it _still_ asks me for the password! 😞 
please see:  https://travis-ci.org/nelsonic/hello-world-node-http-server/builds/384184242#L458
![image](https://user-images.githubusercontent.com/194400/40579862-d3011fba-6129-11e8-88f4-66924b9a3707.png)

The `password` for the SSH key is loaded as an environment variable `SSH_ASKPASS`
but for some reason it is not being "piped" into the `ssh` command.

## What am I doing _wrong_?

Any help _much_ appreciated. (_thanks!_)

**Comment by clarkwang** [comment]
`passh`'s default password prompt is `[Pp]assword: \{0,1\}$`, you need to specify your real prompt. E.g.: `passh -P 'Enter passphrase for key.*:'`.

**Comment by nelsonic** [comment]
@clarkwang thanks! I will try it.
