### ISSUE TITLE
hide password prompt...

### ISSUE THREAD

**Issue by masavini** [clarkwang/passh#3]
hi,
is it possibile to hide the password prompt just like sshpass does?
this is kind of an issue mostly when redirecting command output...
example:
```
$ passh -p password user@host pwd > out
$ cat out
user@host's password:
/home/user
$
$ sshpass -p password user@host pwd > out
$ cat out
/home/user
```

**Comment by masavini** [comment]
just found a forker who just did that:
https://github.com/brunomgalmeida/passh/commit/63e3c03b04211733a8a8e0fdcc6b00c833e25fef#diff-0d215611d71266122acf1cb3dc742ca0

**Comment by clarkwang** [comment]
> just found a forker who just did that:
> [brunomgalmeida@63e3c03#diff-0d215611d71266122acf1cb3dc742ca0](https://github.com/brunomgalmeida/passh/commit/63e3c03b04211733a8a8e0fdcc6b00c833e25fef#diff-0d215611d71266122acf1cb3dc742ca0)

That'll not solve all the problems. With `passh`, in the output all NEWLINEs will be `\r\n` instead of `\n`. And just like `sshpass` its kind of a hack. Personally I'd handle the output on my own requirement.

**Comment by masavini** [comment]
thanks for your hint...

i don't know anything about c, but this seems to be the relevant part:
```
        -        write2(STDOUT_FILENO, fd_from_pty, cache + ncache, nread);
        +        // Password prompt found
        +        if ( regexec(&g.opt.re_prompt, cache, 1, re_match, 0) == 0) {
        +            if (! g.opt.quiet ) {
        +                write2(STDOUT_FILENO, fd_from_pty, cache + ncache, nread);
        +            }
        +            // write(STDOUT_FILENO, "quiet", strlen("quiet") );
        +            // write(STDOUT_FILENO, cache, strlen(cache) );
        +        }else {
        +            write2(STDOUT_FILENO, fd_from_pty, cache + ncache, nread);
        +        }
```

it seems to me like brunomgalmeida just added a check to omit the write2 command if the password prompt is found...
the write2 commands are identical in your and his code and i really can't see any other relevant difference...

how do you output `\n` instead of `\r\n`?

**Comment by masavini** [comment]
you right, i didn't notice that..
even more, brunomgalmeida's `passh` version prints no output when it should contain just one line:
```
$ # clarkwang
$ passh -q -p password user@host pwd > t
$ cat t
user@host's password:
/home/user
$
$ # brunomgalmeida
$ passh -q -p password user@host pwd
$ cat t
$
```
