### ISSUE TITLE
Please set a license

### ISSUE THREAD

**Issue by lovesegfault** [clarkwang/passh#5]
I am trying to [package `passh` to NixOS](https://github.com/NixOS/nixpkgs/pull/82289) but the fact that there is no license is a bit scary, and makes it hard for this to be merged.

Could you please [choose a license](https://choosealicense.com/)?

Thank you!

**Comment by clarkwang** [comment]
Updated with GPLv3 license. Please see if it works for you.

**Comment by lovesegfault** [comment]
It's fine with me, thank you!
