### ISSUE TITLE
Thank your very much for this program!

### ISSUE THREAD

**Issue by evandrocoan** [clarkwang/passh#8]
Just saying thanks!

I also would like to share that I can use this for more than just inputting the password. For exemple, for unison, I could use this to both enter the password and answer yes to the question `Proceed with propagating updates` with the `unison` bidirecional sync tool:
1. `passh -P 'Proceed with propagating updates' -p y passh -P '[Pp]assword: \{0,1\}$' -p password unison ...` 

`unison` has the builtin option called `-batch` to answer yest to this question `Proceed with propagating updates`, but I had to manually answer yes because the `-batch` option also implies to ignore conflict and fail silently. But I would not like for it to fail silently, but ask for my input. Then, putting `passh` to answer `y` to the input question `Proceed with propagating updates`  fixed my problem because when there is a conflict, `y` is not a valid answer (but `f, <`, etc).

**Comment by clarkwang** [comment]
You can try https://github.com/clarkwang/sexpect for this kind of (or more complicated) scenarios. :)
